build: off

version: 0.1.0.{build}

skip_commits:
  message: /updated readme.*|update readme.*s/


environment:
  GitHubKey:
    secure: kRcPGJDgkDM3vWLBngLtejusvA3J5kHWoxFzvb4VeidS5EJzEUx0JOxkM+vrDE0j
    
    
# Kick off the CI/CD pipeline
test_script:
  - ps: $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubKey):x-oauth-basic@github.com`n"
  - git config --global user.email "tjames192@gmail.com"
  - git config --global user.name "Tony James"
  - git config --global core.autocrlf true
  - git config --global core.safecrlf false
  - ps: write-host "calling build.ps1"
  - ps: . .\build.ps1